import Head from "next/head";
import LandingPage from "../components/LandingPage";
import Header from "~/components/Header";
import Footer from "~/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <LandingPage />
      <Footer />
    </>
  );
}
