import Head from "next/head";
import { Toaster } from "react-hot-toast";
import ResumeList from "../components/ResumeList";
import Footer from "~/components/Footer";
import Header from "~/components/Header";

export default function Resume() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Toaster />
      <ResumeList />
      <Footer />
    </>
  );
}
